// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ApiWorld.Model
{
    public class ApisResult
    {
        [JsonProperty("apis")]
        public IList<Api> Apis { get; set; }

        [JsonProperty("total")]
        public int Total { get; set; }
    }
}
